accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    search_project,
    AddNotesCreateView,
)

urlpatterns = [
    path("home", search_project, name="home"),
    path("project", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("search_project/", search_project, name="search_project"),
    path(
        "<int:project_id>/create_notes/",
        AddNotesCreateView.as_view(),
        name="add_note",
    ),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskListView, TaskUpdateView, TaskCreateView

urlpatterns = [
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    # path("users/", include("users.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return self.name


class AddNotes(models.Model):
    note = models.TextField(null=True)
    project = models.ForeignKey(
        "projects.Project", related_name="notes", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class User(models.Model):
    user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="users"
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from projects.models import Project, AddNotes
from itertools import chain
from tasks.models import Task
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


def search_project(request):
    """search function"""
    if request.method == "POST":
        query_name = request.POST.get("name", None)
        if query_name:
            projects = Project.objects.filter(name__contains=query_name)
            tasks = Task.objects.filter(name__contains=query_name)
            results = chain(projects, tasks)
            return render(
                request,
                "projects/search_project.html",
                {"results": results},
            )

    return render(request, "projects/search_project.html")


class AddNotesCreateView(LoginRequiredMixin, CreateView):
    model = AddNotes
    template_name = "projects/create_notes.html"
    fields = ["note"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])

    def form_valid(self, form):
        note = form.save(commit=False)
        project_id = self.kwargs["project_id"]
        note.project = Project.objects.get(id=project_id)
        note.save()
        return redirect("show_project", pk=project_id)

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task

# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])

users/views.py
from django.shortcuts import render

# Create your views here.

projects/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Project Alpha</title>
</head>

<body>
    <header>
        <nav class="navbar bg-light">
            <div class="container-fluid">
                <h1>
                    
                    <a class="nav-link" href="{% url 'home'%}"><mark>Checkify</mark></a>
                    
                </h1>
            <ul>
                {% if user.is_authenticated %}
                    <li class= "nav-item">
                        <a class="nav-link" href="{% url 'show_my_tasks'%}">Tasks</a>
                    </li>
                    <li class= "nav-item">
                        <a class="nav-link" href="{% url 'list_projects'%}">Projects</a>
                    </li>
                    <li class= "nav-item">
                        <a class="nav-link" href="{% url 'logout'%}">Logout</a>
                    </li>
                    
                {%else%}
                    <li class= "nav-item">
                        <a class="nav-link" href="{% url 'login'%}">Login</a>
                    </li>
                    <li class= "nav-item">
                        <a class="nav-link" href="{% url 'signup'%}">Signup</a>
                    </li>
                
                {%endif%}
            
            </ul>
            <div>
                <form action="{% url 'search_project' %}" method="POST" class="d-flex justify-content-end" role="search">
                    {% csrf_token %} 
                    <input class="form-control ml-5" type="text" name="name">
                    <button class="btn btn-outline" type="submit">Search</button>
                </form>
            </div>
        </div>
        </nav>
        <img src= "{% static 'img/logo.png' %}" class="rounded mx-auto d-block" alt="Responsive image" width='200px' >
    </header>
    {% block content %}
    {% endblock content %}
    <footer>
        <div class="text-center p-3 bg-light" >
            © 2022 Copyright: CiseBaba
        </div>
    </footer
</body>

</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="mb-3 row">
            <h1>Create a new project</h1>
            <form method="post" >
                <table>
                    {% csrf_token %}
                    {{form.as_table}}
                    <tr>
                        <td>&nbsp;</td>
                        <td><button class="btn btn-light ">Create</button></td>
                    </tr>
                </table>
            </form>
        </div>
    </main>

{% endblock content %}

projects/templates/projects/create_notes.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="mb-3 row">
            <h1>Add a note</h1>
            <form method="post">
                <table>
                    {% csrf_token %}
                    {{form.as_table}}
                    <tr>
                        <td>&nbsp;</td>
                        <td><button class="btn btn-light ">Create</button></td>
                    </tr>
            </form>
        </div>
    </main>

{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div>
            <h1>{{project.name}}</h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <p>
                <a href="{% url 'create_task'%}" class="btn btn-light">Create a new task</a>
            </p>
            {%if project.tasks.all|length == 0%}
                <p>This project has no tasks</p>
            {%else%}
                <table class="table table-success table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        <tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.assignee}}</td>
                                <td>{{task.start_date}}</td>
                                <td>{{task.due_date}}</td>
                                <td>{{task.is_completed|yesno}}</td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>
            {%endif%}
            <p class="create-link">
                <a href="{% url 'add_note' project.id %}" class="btn btn-light">Add a note</a>
            </p>
            {% for note in project.notes.all%}
            <div class="card">
                <p class = "notes">Comment: {{note.note}}</p>
            </div>
            {%endfor%}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/home.html
{% extends 'base.html' %}
{% block content %}

    <img src="{% static "/img/logo.png" %}" id="flip" alt="instagram">
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Projects</h1>
            <p>
                <a href="{% url 'create_project'%}" class="btn btn-light">Create a new project</a>
            </p>
            {% if project_list|length == 0 %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table class="table table-success table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                            <tr>
                            </thead>
                            <tbody>
                            {%for project in project_list%}
                                    <tr>
                                        <td>
                                            <a href="{% url 'show_project' project.id %}">{{project.name}}<a/>
                                        </td>
                                        <td>{{project.tasks.all|length}}</td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                </table>   
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/search_project.html
{% extends 'base.html' %}
{% block content %}

    {% for result in results %}
        <h3>You searched for</h3>
        <a href= "{% url 'show_project' result.pk %}">{{result.name}}</a>
    {%empty%}
        <h3>Hey! You forgot to search a Project or Task</h3>
    {% endfor %}
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="mb-3 row">
            <h1>Create a new task</h1>
            <form method="post">
                <table>
                    {% csrf_token %}
                    {{form.as_table}}
                    <tr>
                        <td>&nbsp;</td>
                        <td><button class="btn btn-light ">Create</button></td>
                    </tr>
            </form>
        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Tasks</h1>
            {% if task_list|length == 0%}
                <p>You have no tasks</p>
            {%else%}
            <table class="table table-success table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    <tr>
                </thead>
                <tbody>
                {% for task in task_list %}
                    <tr>
                        <td>{{task.name}}</td>
                        <td>{{task.assignee}}</td>
                        <td>{{task.start_date}}</td>
                        <td>{{task.due_date}}</td>
                        <td>
                            {% if task.is_completed == False %}
                                <form method="post" action="{% url 'complete_task' task.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="is_completed" value="True">
                                    <button class="btn btn-light">Complete</button>
                                </form>
                            {%else%}
                                {{task.is_completed|yesno:"✅,  ,  "}}
                            {%endif%}
                        </td>
                    </tr>
                {%endfor%}
                </tbody>
            </table>
            {%endif%}
        </div>
    </main>
{%endblock content%}